# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'VidArchiverUI.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1036, 803)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("VidArchiver.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.formLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.formLayoutWidget.setGeometry(QtCore.QRect(10, 0, 1021, 61))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout_4 = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout_4.setContentsMargins(0, 0, 0, 0)
        self.formLayout_4.setObjectName("formLayout_4")
        self.lbl_vidArchPfad = QtWidgets.QLabel(self.formLayoutWidget)
        self.lbl_vidArchPfad.setObjectName("lbl_vidArchPfad")
        self.formLayout_4.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.lbl_vidArchPfad)
        self.le_vidArchPfad = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.le_vidArchPfad.setObjectName("le_vidArchPfad")
        self.formLayout_4.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.le_vidArchPfad)
        self.lbl_quelle = QtWidgets.QLabel(self.formLayoutWidget)
        self.lbl_quelle.setObjectName("lbl_quelle")
        self.formLayout_4.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.lbl_quelle)
        self.cb_quelle = QtWidgets.QComboBox(self.formLayoutWidget)
        self.cb_quelle.setObjectName("cb_quelle")
        self.formLayout_4.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.cb_quelle)
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(10, 80, 1021, 601))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.lbl_filmeQuelle = QtWidgets.QLabel(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.lbl_filmeQuelle.setFont(font)
        self.lbl_filmeQuelle.setObjectName("lbl_filmeQuelle")
        self.verticalLayout_2.addWidget(self.lbl_filmeQuelle)
        self.tbl_film = QtWidgets.QTableView(self.horizontalLayoutWidget)
        self.tbl_film.setAutoFillBackground(False)
        self.tbl_film.setStyleSheet("background-color: rgb(210, 215, 203);")
        self.tbl_film.setAlternatingRowColors(True)
        self.tbl_film.setObjectName("tbl_film")
        self.verticalLayout_2.addWidget(self.tbl_film)
        self.horizontalLayout_2.addLayout(self.verticalLayout_2)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_2.addLayout(self.verticalLayout_3)
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(10, 680, 1021, 80))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.btn_playVideo = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_playVideo.sizePolicy().hasHeightForWidth())
        self.btn_playVideo.setSizePolicy(sizePolicy)
        self.btn_playVideo.setDefault(True)
        self.btn_playVideo.setObjectName("btn_playVideo")
        self.horizontalLayout_3.addWidget(self.btn_playVideo)
        spacerItem1 = QtWidgets.QSpacerItem(60, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.btn_unlinkVideo = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_unlinkVideo.sizePolicy().hasHeightForWidth())
        self.btn_unlinkVideo.setSizePolicy(sizePolicy)
        self.btn_unlinkVideo.setObjectName("btn_unlinkVideo")
        self.horizontalLayout_3.addWidget(self.btn_unlinkVideo)
        self.btn_linkVideo = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_linkVideo.sizePolicy().hasHeightForWidth())
        self.btn_linkVideo.setSizePolicy(sizePolicy)
        self.btn_linkVideo.setObjectName("btn_linkVideo")
        self.horizontalLayout_3.addWidget(self.btn_linkVideo)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1036, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "VideoArchiver"))
        self.lbl_vidArchPfad.setText(_translate("MainWindow", "Pfad zum Video-Archiv"))
        self.lbl_quelle.setText(_translate("MainWindow", "Quelle im VideoArchiv"))
        self.lbl_filmeQuelle.setText(_translate("MainWindow", "Filme in der Quelle"))
        self.btn_playVideo.setText(_translate("MainWindow", "Film abspielen"))
        self.btn_unlinkVideo.setText(_translate("MainWindow", "Video aus Pfad entfernen"))
        self.btn_linkVideo.setText(_translate("MainWindow", "Video dem Pfad &zufügen"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

