# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'VidArchiverUI6.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1441, 827)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("VidArchiver.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("QLabel: {\n"
"    font: 75 10pt \"MS Shell Dlg 2\";\n"
"    background-color: rgb(208, 199, 255);\n"
"};\n"
"")
        self.centralwidget.setObjectName("centralwidget")
        self.formLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.formLayoutWidget.setGeometry(QtCore.QRect(10, 0, 511, 61))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout_4 = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout_4.setContentsMargins(0, 0, 0, 0)
        self.formLayout_4.setObjectName("formLayout_4")
        self.lbl_vidArchPfad = QtWidgets.QLabel(self.formLayoutWidget)
        self.lbl_vidArchPfad.setObjectName("lbl_vidArchPfad")
        self.formLayout_4.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.lbl_vidArchPfad)
        self.le_vidArchPfad = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.le_vidArchPfad.setObjectName("le_vidArchPfad")
        self.formLayout_4.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.le_vidArchPfad)
        self.lbl_quelle = QtWidgets.QLabel(self.formLayoutWidget)
        self.lbl_quelle.setObjectName("lbl_quelle")
        self.formLayout_4.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.lbl_quelle)
        self.cb_quelle = QtWidgets.QComboBox(self.formLayoutWidget)
        self.cb_quelle.setObjectName("cb_quelle")
        self.formLayout_4.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.cb_quelle)
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(10, 80, 1411, 641))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout_2.setSizeConstraint(QtWidgets.QLayout.SetNoConstraint)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.lbl_filmeQuelle = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.lbl_filmeQuelle.setStyleSheet("font: 75 10pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(184, 191, 255);")
        self.lbl_filmeQuelle.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_filmeQuelle.setObjectName("lbl_filmeQuelle")
        self.verticalLayout_2.addWidget(self.lbl_filmeQuelle)
        self.tbl_film = QtWidgets.QTableWidget(self.horizontalLayoutWidget)
        self.tbl_film.setMinimumSize(QtCore.QSize(300, 0))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.tbl_film.setFont(font)
        self.tbl_film.setStyleSheet("background-color: rgb(255, 255, 203);\n"
"alternate-background-color: rgb(170, 255, 127);")
        self.tbl_film.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tbl_film.setAlternatingRowColors(True)
        self.tbl_film.setSelectionMode(QtWidgets.QAbstractItemView.ExtendedSelection)
        self.tbl_film.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tbl_film.setRowCount(5)
        self.tbl_film.setObjectName("tbl_film")
        self.tbl_film.setColumnCount(1)
        item = QtWidgets.QTableWidgetItem()
        self.tbl_film.setHorizontalHeaderItem(0, item)
        self.tbl_film.verticalHeader().setDefaultSectionSize(25)
        self.verticalLayout_2.addWidget(self.tbl_film)
        self.groupBox_4 = QtWidgets.QGroupBox(self.horizontalLayoutWidget)
        self.groupBox_4.setMinimumSize(QtCore.QSize(0, 50))
        self.groupBox_4.setStyleSheet("background-color: rgb(200, 200, 200);")
        self.groupBox_4.setObjectName("groupBox_4")
        self.btn_delPrep = QtWidgets.QPushButton(self.groupBox_4)
        self.btn_delPrep.setGeometry(QtCore.QRect(11, 21, 130, 23))
        self.btn_delPrep.setMinimumSize(QtCore.QSize(130, 0))
        self.btn_delPrep.setObjectName("btn_delPrep")
        self.btn_renamePrep = QtWidgets.QPushButton(self.groupBox_4)
        self.btn_renamePrep.setGeometry(QtCore.QRect(150, 20, 130, 23))
        self.btn_renamePrep.setObjectName("btn_renamePrep")
        self.btn_showPrepVideo = QtWidgets.QPushButton(self.groupBox_4)
        self.btn_showPrepVideo.setGeometry(QtCore.QRect(288, 21, 130, 23))
        self.btn_showPrepVideo.setObjectName("btn_showPrepVideo")
        self.verticalLayout_2.addWidget(self.groupBox_4)
        self.formLayout_2 = QtWidgets.QFormLayout()
        self.formLayout_2.setObjectName("formLayout_2")
        self.le_PrepFilm = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.le_PrepFilm.setObjectName("le_PrepFilm")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.le_PrepFilm)
        self.label_7 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_7.setObjectName("label_7")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_7)
        self.le_PrepFilmGr = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.le_PrepFilmGr.setObjectName("le_PrepFilmGr")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.le_PrepFilmGr)
        self.label_8 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_8.setObjectName("label_8")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_8)
        self.le_PrepFilmDat = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.le_PrepFilmDat.setObjectName("le_PrepFilmDat")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.le_PrepFilmDat)
        self.label_6 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_6.setObjectName("label_6")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_6)
        self.verticalLayout_2.addLayout(self.formLayout_2)
        self.horizontalLayout_2.addLayout(self.verticalLayout_2)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.lbl_filmOrdner = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.lbl_filmOrdner.setStyleSheet("font: 75 10pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(184, 191, 255);")
        self.lbl_filmOrdner.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_filmOrdner.setObjectName("lbl_filmOrdner")
        self.verticalLayout_3.addWidget(self.lbl_filmOrdner)
        self.lst_vidPfad_Main = QtWidgets.QListWidget(self.horizontalLayoutWidget)
        self.lst_vidPfad_Main.setMaximumSize(QtCore.QSize(16777215, 120))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.lst_vidPfad_Main.setFont(font)
        self.lst_vidPfad_Main.setStyleSheet("background-color: rgb(255, 255, 32);")
        self.lst_vidPfad_Main.setObjectName("lst_vidPfad_Main")
        self.verticalLayout_3.addWidget(self.lst_vidPfad_Main)
        self.lst_vidPfad_Sub = QtWidgets.QListWidget(self.horizontalLayoutWidget)
        self.lst_vidPfad_Sub.setMaximumSize(QtCore.QSize(16777215, 280))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.lst_vidPfad_Sub.setFont(font)
        self.lst_vidPfad_Sub.setStyleSheet("background-color: rgb(250, 220, 160);")
        self.lst_vidPfad_Sub.setObjectName("lst_vidPfad_Sub")
        self.verticalLayout_3.addWidget(self.lst_vidPfad_Sub)
        self.lst_vidPfad_Base = QtWidgets.QListWidget(self.horizontalLayoutWidget)
        self.lst_vidPfad_Base.setMaximumSize(QtCore.QSize(16777215, 180))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.lst_vidPfad_Base.setFont(font)
        self.lst_vidPfad_Base.setStyleSheet("background-color: rgb(255, 253, 166);")
        self.lst_vidPfad_Base.setObjectName("lst_vidPfad_Base")
        self.verticalLayout_3.addWidget(self.lst_vidPfad_Base)
        self.horizontalLayout_2.addLayout(self.verticalLayout_3)
        self.verticalLayout_9 = QtWidgets.QVBoxLayout()
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.lbl_ArchivFilm = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.lbl_ArchivFilm.setStyleSheet("font: 75 12pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(184, 191, 255);\n"
"")
        self.lbl_ArchivFilm.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_ArchivFilm.setObjectName("lbl_ArchivFilm")
        self.verticalLayout_9.addWidget(self.lbl_ArchivFilm, 0, QtCore.Qt.AlignTop)
        self.tbl_vorhFilm = QtWidgets.QTableWidget(self.horizontalLayoutWidget)
        self.tbl_vorhFilm.setMinimumSize(QtCore.QSize(300, 0))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.tbl_vorhFilm.setFont(font)
        self.tbl_vorhFilm.setStyleSheet("background-color: rgb(154, 255, 152);\n"
"alternate-background-color: rgb(255, 226, 176);")
        self.tbl_vorhFilm.setEditTriggers(QtWidgets.QAbstractItemView.DoubleClicked)
        self.tbl_vorhFilm.setAlternatingRowColors(True)
        self.tbl_vorhFilm.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.tbl_vorhFilm.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tbl_vorhFilm.setRowCount(5)
        self.tbl_vorhFilm.setObjectName("tbl_vorhFilm")
        self.tbl_vorhFilm.setColumnCount(1)
        item = QtWidgets.QTableWidgetItem()
        self.tbl_vorhFilm.setHorizontalHeaderItem(0, item)
        self.tbl_vorhFilm.verticalHeader().setDefaultSectionSize(25)
        self.verticalLayout_9.addWidget(self.tbl_vorhFilm)
        self.groupBox_2 = QtWidgets.QGroupBox(self.horizontalLayoutWidget)
        self.groupBox_2.setMinimumSize(QtCore.QSize(0, 50))
        self.groupBox_2.setStyleSheet("background-color: rgb(200, 200, 200);")
        self.groupBox_2.setObjectName("groupBox_2")
        self.btn_del = QtWidgets.QPushButton(self.groupBox_2)
        self.btn_del.setGeometry(QtCore.QRect(11, 21, 130, 23))
        self.btn_del.setMinimumSize(QtCore.QSize(130, 0))
        self.btn_del.setObjectName("btn_del")
        self.btn_rename = QtWidgets.QPushButton(self.groupBox_2)
        self.btn_rename.setGeometry(QtCore.QRect(150, 20, 130, 23))
        self.btn_rename.setObjectName("btn_rename")
        self.btn_showArchVideo = QtWidgets.QPushButton(self.groupBox_2)
        self.btn_showArchVideo.setGeometry(QtCore.QRect(288, 21, 130, 23))
        self.btn_showArchVideo.setObjectName("btn_showArchVideo")
        self.verticalLayout_9.addWidget(self.groupBox_2)
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.label_3 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.le_ArchivFilm = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.le_ArchivFilm.setObjectName("le_ArchivFilm")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.le_ArchivFilm)
        self.label_4 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.le_ArchivFilmGr = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.le_ArchivFilmGr.setObjectName("le_ArchivFilmGr")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.le_ArchivFilmGr)
        self.label_5 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_5.setObjectName("label_5")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.le_ArchivFilmDat = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.le_ArchivFilmDat.setObjectName("le_ArchivFilmDat")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.le_ArchivFilmDat)
        self.verticalLayout_9.addLayout(self.formLayout)
        self.horizontalLayout_2.addLayout(self.verticalLayout_9)
        self.horizontalGroupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.horizontalGroupBox_2.setGeometry(QtCore.QRect(10, 720, 1411, 41))
        self.horizontalGroupBox_2.setObjectName("horizontalGroupBox_2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.horizontalGroupBox_2)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem = QtWidgets.QSpacerItem(100, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.btn_linkVideo = QtWidgets.QPushButton(self.horizontalGroupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_linkVideo.sizePolicy().hasHeightForWidth())
        self.btn_linkVideo.setSizePolicy(sizePolicy)
        self.btn_linkVideo.setObjectName("btn_linkVideo")
        self.horizontalLayout_3.addWidget(self.btn_linkVideo)
        spacerItem1 = QtWidgets.QSpacerItem(240, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.btn_pfadNeu = QtWidgets.QPushButton(self.horizontalGroupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_pfadNeu.sizePolicy().hasHeightForWidth())
        self.btn_pfadNeu.setSizePolicy(sizePolicy)
        self.btn_pfadNeu.setMinimumSize(QtCore.QSize(200, 0))
        self.btn_pfadNeu.setObjectName("btn_pfadNeu")
        self.horizontalLayout_3.addWidget(self.btn_pfadNeu)
        spacerItem2 = QtWidgets.QSpacerItem(60, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem2)
        self.btn_unlinkVideo = QtWidgets.QPushButton(self.horizontalGroupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_unlinkVideo.sizePolicy().hasHeightForWidth())
        self.btn_unlinkVideo.setSizePolicy(sizePolicy)
        self.btn_unlinkVideo.setObjectName("btn_unlinkVideo")
        self.horizontalLayout_3.addWidget(self.btn_unlinkVideo)
        spacerItem3 = QtWidgets.QSpacerItem(120, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem3)
        self.btn_ende = QtWidgets.QPushButton(self.horizontalGroupBox_2)
        self.btn_ende.setObjectName("btn_ende")
        self.horizontalLayout_3.addWidget(self.btn_ende)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(950, 0, 261, 41))
        self.label_2.setStyleSheet("font: 87 24pt \"Arial Black\";")
        self.label_2.setObjectName("label_2")
        self.lbl_version = QtWidgets.QLabel(self.centralwidget)
        self.lbl_version.setGeometry(QtCore.QRect(1210, 40, 161, 16))
        self.lbl_version.setObjectName("lbl_version")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(600, 760, 161, 20))
        self.label.setObjectName("label")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1441, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.btn_ende.clicked['bool'].connect(MainWindow.close)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "VideoArchiver"))
        self.lbl_vidArchPfad.setText(_translate("MainWindow", "Pfad zum Video-Archiv"))
        self.lbl_quelle.setText(_translate("MainWindow", "Quelle (Prep-Ordner)"))
        self.lbl_filmeQuelle.setText(_translate("MainWindow", "Filme in der Quelle"))
        item = self.tbl_film.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Film"))
        self.groupBox_4.setTitle(_translate("MainWindow", "Video im Prep-Ordner ..."))
        self.btn_delPrep.setText(_translate("MainWindow", "&löschen - F8"))
        self.btn_renamePrep.setText(_translate("MainWindow", "&umbenennen - F6"))
        self.btn_showPrepVideo.setText(_translate("MainWindow", "&zeigen - F3"))
        self.label_7.setText(_translate("MainWindow", "Größe"))
        self.label_8.setText(_translate("MainWindow", "Datum"))
        self.label_6.setText(_translate("MainWindow", "Film"))
        self.lbl_filmOrdner.setText(_translate("MainWindow", "Verfügbare Archiv-Ordner"))
        self.lbl_ArchivFilm.setText(_translate("MainWindow", "Filme im Archiv-Ordner"))
        item = self.tbl_vorhFilm.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Film"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Video im Archiv ..."))
        self.btn_del.setText(_translate("MainWindow", "&löschen"))
        self.btn_rename.setText(_translate("MainWindow", "&umbenennen"))
        self.btn_showArchVideo.setText(_translate("MainWindow", "&zeigen"))
        self.label_3.setText(_translate("MainWindow", "Film"))
        self.label_4.setText(_translate("MainWindow", "Größe"))
        self.label_5.setText(_translate("MainWindow", "Datum"))
        self.btn_linkVideo.setText(_translate("MainWindow", "Video &in den  Pfad einsortieren - F5"))
        self.btn_pfadNeu.setText(_translate("MainWindow", "neuer Unterordner"))
        self.btn_unlinkVideo.setText(_translate("MainWindow", "Video zuzück in die Quelle - Shift+F5"))
        self.btn_ende.setText(_translate("MainWindow", "Ende"))
        self.label_2.setText(_translate("MainWindow", "Video-Archiver"))
        self.lbl_version.setText(_translate("MainWindow", "VersionsInfo"))
        self.label.setText(_translate("MainWindow", "<---  technische Info: F2   --->"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
